#ifndef _ERRNO_H
#define _ERRNO_H

#include "tertium_cpu.h"

#define E2BIG C_E2BIG
#define EACCES C_EACCES
#define EADDRINUSE C_EADDRINUSE
#define EADDRNOTAVAIL C_EADDRNOTAVAIL
#define EAFNOSUPPORT C_EAFNOSUPPORT
#define EAGAIN C_EAGAIN
#define EALREADY C_EALREADY
#define EBADF C_EBADF
#define EBADMSG C_EBADMSG
#define EBUSY C_EBUSY
#define ECANCELED C_ECANCELED
#define ECHILD C_ECHILD
#define ECONNABORTED C_ECONNABORTED
#define ECONNREFUSED C_ECONNREFUSED
#define ECONNRESET C_ECONNRESET
#define EDEADLK C_EDEADLK
#define EDESTADDRREQ C_EDESTADDRREQ
#define EDOM C_EDOM
#define EDQUOT C_EDQUOT
#define EEXIST C_EEXIST
#define EFAULT C_EFAULT
#define EFBIG C_EFBIG
#define EHOSTUNREACH C_EHOSTUNREACH
#define EIDRM C_EIDRM
#define EILSEQ C_EILSEQ
#define EINPROGRESS C_EINPROGRESS
#define EINTR C_EINTR
#define EINVAL C_EINVAL
#define EIO C_EIO
#define EISCONN C_EISCONN
#define EISDIR C_EISDIR
#define ELOOP C_ELOOP
#define EMFILE C_EMFILE
#define EMLINK C_EMLINK
#define EMSGSIZE C_EMSGSIZE
#define EMULTIHOP C_EMULTIHOP
#define ENAMETOOLONG C_ENAMETOOLONG
#define ENETDOWN C_ENETDOWN
#define ENETRESET C_ENETRESET
#define ENETUNREACH C_ENETUNREACH
#define ENFILE C_ENFILE
#define ENOBUFS C_ENOBUFS
#define ENODEV C_ENODEV
#define ENOENT C_ENOENT
#define ENOEXEC C_ENOEXEC
#define ENOLCK C_ENOLCK
#define ENOLINK C_ENOLINK
#define ENOMEM C_ENOMEM
#define ENOMSG C_ENOMSG
#define ENOPROTOOPT C_ENOPROTOOPT
#define ENOSPC C_ENOSPC
#define ENOSYS C_ENOSYS
#define ENOTCONN C_ENOTCONN
#define ENOTDIR C_ENOTDIR
#define ENOTEMPTY C_ENOTEMPTY
#define ENOTRECOVERABLE C_ENOTRECOVERABLE
#define ENOTSOCK C_ENOTSOCK
#define ENOTSUP C_ENOTSUP
#define ENOTTY C_ENOTTY
#define ENXIO C_ENXIO
#define EOPNOTSUPP C_EOPNOTSUPP
#define EOVERFLOW C_EOVERFLOW
#define EOWNERDEAD C_EOWNERDEAD
#define EPERM C_EPERM
#define EPIPE C_EPIPE
#define EPROTO C_EPROTO
#define EPROTONOSUPPORT C_EPROTONOSUPPORT
#define EPROTOTYPE C_EPROTOTYPE
#define ERANGE C_ERANGE
#define EROFS C_EROFS
#define ESPIPE C_ESPIPE
#define ESRCH C_ESRCH
#define ESTALE C_ESTALE
#define ETIMEDOUT C_ETIMEDOUT
#define ETXTBSY C_ETXTBSY
#define EWOULDBLOCK C_EWOULDBLOCK
#define EXDEV C_EXDEV
#define ECSTM C_ECSTM

extern int errno;

#endif
