#ifndef _LIMITS_H
#define _LIMITS_H

#include "tertium_cpu.h"

#define NAME_MAX C_NAMEMAX
#define PATH_MAX C_PATHMAX

#define ARG_MAX C_ARGMAX
#define CHILD_MAX C_CHILDMAX
#define HOST_NAME_MAX C_HOSTNAMEMAX
#define LOGIN_NAME_MAX C_LOGINNAMEMAX
#define NGROUPS_MAX C_NGROUPSMAX
#define OPEN_MAX C_OPENMAX
#define PAGE_SIZE C_PAGESIZE
#define SYMLOOP_MAX C_SYMLOOPMAX
#define TTY_NAME_MAX C_TTYNAMEMAX

#define CHAR_BIT C_CHARBIT
#define CHAR_MAX C_CHARMAX
#define UCHAR_MAX C_UCHARMAX
#define INT_MAX C_INTMAX
#define UINT_MAX C_UINTMAX
#define LONG_MAX C_LONGMAX
#define ULONG_MAX C_ULONGMAX
#define SHRT_MAX C_SHRTMAX
#define USHRT_MAX C_USHRTMAX
#define SSIZE_MAX C_SIZEMAX
/* #define SIZE_MAX C_USIZEMAX */
#define LLONG_MAX C_VLONGMAX
#define ULLONG_MAX C_UVLONGMAX
#define CHAR_MIN C_CHARMIN
#define INT_MIN C_INTMIN
#define LONG_MIN C_LONGMIN
#define SHRT_MIN C_SHRTMIN
#define SSIZE_MIN C_SIZEMIN
#define LLONG_MIN C_VLONGMIN

#endif
